### ISSUE TITLE
1. Image Analysis

### ISSUE THREAD

**Issue by hczirjek** [raduf24/VisualMoodTracker#1]
We will implement Microsoft Azure (https://azure.microsoft.com/en-us/).
As output data/result we will get a JSON file which contains data about the analyzed image of a person.
Each block in JSON file includes time ranges, transcript lines, OCR lines, sentiments, faces, and block thumbnails.
We can implement the API on Front-End by using Javascript or on Back-End by using C# (Azure for .NET)(https://docs.microsoft.com/en-us/dotnet/azure/).
We will show the results on a UI using graphs.

**Comment by OlteanCalin** [comment]
Emotion API for C# 
https://docs.microsoft.com/en-us/azure/cognitive-services/emotion/quickstarts/csharp

Changes made in the Emotion feature combined in the Face API (url changed to https://westcentralus.api.cognitive.microsoft.com/face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false&returnFaceAttributes=emotion )

https://westcentralus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236/console
